### PR TITLE
Fix verifySSL parameter

### PR DESCRIPTION
**Pull request by IntelliJAbhishek**
Axios does not support verifySSL option. We need different approach using agent to support this parameter.
Refer this- https://github.com/axios/axios/issues/535

### CODE REVIEW

**Comment by IntelliJAbhishek** [comment]
@claudiosanches why dependency check failure?

**Comment by claudiosanches** [comment]
This setting is already correct, when using `strictSSL` as false should not verify for a valid SSL certificate.

**Comment by IntelliJAbhishek** [comment]
@claudiosanches there is no such parameters strictSSL in axios

**Comment by IntelliJAbhishek** [comment]
If we use strictSSL false it will not work with self signed certificate. Need to use agent strategy.

**Comment by claudiosanches** [comment]
I'll remove this option for now then.

**Comment by IntelliJAbhishek** [comment]
You can support it .. check my pr.. i closed this pr because this library is not working in react-native. But it will work in other js frameworks

**Comment by claudiosanches** [comment]
@IntelliJAbhishek we need to support both, if you found issues on react-native, please open new issues so we can work on it.

**Comment by IntelliJAbhishek** [comment]
@claudiosanches I will PR for react-native after testing.

**Comment by claudiosanches** [comment]
@IntelliJAbhishek thanks!

**Pull request closed without merging**
